# Generated by Django 3.2.14 on 2022-07-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_auto_20220719_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
